FROM python:latest
## currently commented out because I don't have an interent connection
# RUN pip install ipython toolz hypothesis mypy
RUN mkdir -p /opt/demo
WORKDIR /opt/demo
# CMD ipython
CMD python
